version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_DB_FILE: /run/secrets/db_name
      PGDATA: //var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}"
    secrets:
      - db_password
      - db_username
      - db_name
    healthcheck:
      # test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: backend
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      PORT: ${PORT}
      DB_HOSTNAME: database
      DB_PORT: ${DB_PORT}
      DB_NAME_FILE: /run/secrets/db_name
      DB_USERNAME_FILE: /run/secrets/db_username
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - secret_key
      - db_password
      - db_username
      - db_name
    ports:
      - "8000:${PORT}"
    depends_on:
      database:
        condition: service_healthy
    restart: always
    volumes:
      - backend-data:/usr/home/backend

secrets:
  secret_key:
    file: secrets/secret_key.txt
  db_password:
    file: secrets/db_password.txt
  db_username:
    file: secrets/db_username.txt
  db_name:
    file: secrets/db_name.txt

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mount/db
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mount/backend