# Generated by Django 4.1 on 2023-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='post',
        ),
    ]
